
    
   <script type="text/javascript">
//<![CDATA[
 require([
    'jquery',
    'hello'
], function($, alert) {
   $('.swatch-option').on('click', function(event){
       alert 'hellooooo';
//        alert({
//            content: $(event.target).parent().val()
//        })
      })
   }
 );
//]]>
</script>






<script>// <![CDATA[
        require([
            'jquery',
            'hello'
        ], function ($) {
           $('.swatch-option').click(function(){
               
               alert('helloworld');
           });
          // $('.product-info-main').HelloWorld();
        });
        // ]]>
    </script>